version: "3.7"
services:
  db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: kinder
      POSTGRES_USER: kinder
      POSTGRES_PASSWORD: kinder123
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
   postgres-data:
     driver: local