CREATE TABLE photo(
    id BIGSERIAL PRIMARY KEY,
    url VARCHAR NOT NULL
);

ALTER TABLE "user" ADD COLUMN photo_id BIGINT;
ALTER TABLE "user" ADD COLUMN user_id VARCHAR;
ALTER TABLE "user" ADD COLUMN description VARCHAR;
ALTER TABLE "user" ADD COLUMN city VARCHAR;
ALTER TABLE "user" ADD FOREIGN KEY (photo_id) REFERENCES photo(id);