ALTER TABLE ticket
ADD user_id INTEGER NOT NULL;

ALTER TABLE ticket
ADD event_id INTEGER NOT NULL;

ALTER TABLE ticket
ADD FOREIGN KEY (user_id) REFERENCES "user"(id) ON DELETE CASCADE;

ALTER TABLE ticket
ADD FOREIGN KEY (event_id) REFERENCES event(id) ON DELETE CASCADE;